### PR TITLE
Resource state fixes

### LINKED ISSUE #61: The UI uses the wrong Kubernetes CRD
At the moment when creating the kubernetes cluster CRD it's pushing the GKECredentials as the reference `spec.Provider`. This should be the GKE cluster itself ... This was only caught as i've added the wait on deletion added the api but it's was injected with the wrong details

### LINKED ISSUE #64: Deletion progress isn't instant, page refresh is required to get status
After clicking the button to delete the cluster the k8s won't delete until the provider has been removed, the status is changed to 'Deleting'. 

- on first delete click the page errors
- after refreshing the page the cluster is shown as deleting
- the auto refresh polls the cluster but after the cluster is deleted the page errors until you refresh.

### LINKED ISSUE #67: Deleting Namespaces
When you delete the namespace it doesn't check the status like the clusters and so it's deleted from the UI before it's actually deleted.

### LINKED ISSUE #70: Namespace Deletion Bug
There appears to be a slight bug; if you delete a namespace and you have more than one, two namespace disappear from the table. A refresh does bring down the non deleted one though.

### PR DESCRIPTION
**Pull request by davet1985**
* create cluster resource fix for `spec.provider` - it should be the `GKE` resource not `GKECredentials`
* deleting clusters now auto refreshes and the row is removed when it's deleted
* same with namespace claims
* showing deleted time when it's available

Closes #61 
Closes #64
Closes #67 
Closes #70

### CODE REVIEW

File: lib/components/team/Cluster.js [hunk 1]
```diff
@@ -61,9 +67,10 @@ class Cluster extends AutoRefreshComponent {
       const state = copy(this.state)
       const cluster = state.cluster
       await apiRequest(null, 'delete', `/teams/${team}/clusters/${cluster.metadata.name}`)
-      await apiRequest(null, 'delete', `/teams/${team}/gkes/${cluster.metadata.name}`)
-      state.cluster.deleted = true
+      cluster.status.status = 'Deleting'
+      cluster.metadata.deletionTimestamp = new Date()
```
Comment (mrsheepuk) [inline lib/components/team/Cluster.js]: No longer deleteing the resource from /teams/${team}/gkes/... ? Is that correct?

Comment (davet1985) [reply lib/components/team/Cluster.js]: Yep that's taken care of Kore 👍
