### PR TITLE
Team page resource updates

### LINKED ISSUE #77: Cluster details don't update when switching between teams
Repro steps:

1. Create two teams
2. Create a cluster in each team
3. Click the team name on the left

Expected result:
* Clusters section shows list of clusters for that team.

Actual result:
* Clusters section shows clusters for whichever team was opened first.

### PR DESCRIPTION
**Pull request by davet1985**
Ensuring the resources are properly refreshed when switching between teams

* fixing `componentDidUpdate` in `[name].js` to use new props instead of previous ones
* adding `componentDidUpdate` to `Cluster` and `NamespaceClaim` components in order to update state when props are changed
* same for the `InviteLink` component, a new link should be generated when the team is switched

Closes #77

### CODE REVIEW

File: lib/components/team/InviteLink.js [hunk 1]
```diff
@@ -19,20 +19,27 @@ class InviteLink extends React.Component {
...
-      .then(inviteLink => {
-        const state = copy(this.state)
-        if (typeof inviteLink !== 'string') {
-          state.dataError = true
-        }
-        state.inviteLink = inviteLink
-        state.dataLoading = false
-        this.setState(state)
-      })
+    this.fetchComponentData()
```
Comment (mrsheepuk) [inline lib/components/team/InviteLink.js]: should this have an await?

File: lib/components/team/InviteLink.js [hunk 2]
```diff
@@ -19,20 +19,27 @@ class InviteLink extends React.Component {
...
+  }
+
+  componentDidUpdate(prevProps) {
+    if (prevProps.team !== this.props.team) {
+      const state = copy(this.state)
+      state.dataLoading = true
+      this.setState(state)
+
+      this.fetchComponentData()
```
Comment (mrsheepuk) [inline lib/components/team/InviteLink.js]: shoudl this also have an await?

File: lib/components/team/InviteLink.js (hunk 1 above)
Comment (davet1985) [reply lib/components/team/InviteLink.js]: No, as the function does not need to wait for the promise to finish.

Also, you cannot `await` here due to being unable to make `componentDidMount` an `async` function, instead, we would need to return the promise and use `.then`

File: lib/components/team/InviteLink.js (hunk 2 above)
Comment (davet1985) [reply lib/components/team/InviteLink.js]: Same as above

File: lib/components/team/InviteLink.js (hunk 1 above)
Comment (mrsheepuk) [reply lib/components/team/InviteLink.js]: as discussed, happy to approve
